# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMessEdit(object):
    def setupUi(self, WindowMessEdit):
        WindowMessEdit.setObjectName("WindowMessEdit")
        WindowMessEdit.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WindowMessEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 450, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 450, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBoxDelPerson = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDelPerson.setGeometry(QtCore.QRect(70, 30, 261, 17))
        self.checkBoxDelPerson.setObjectName("checkBoxDelPerson")
        self.textEditTimePause = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditTimePause.setGeometry(QtCore.QRect(70, 60, 31, 31))
        self.textEditTimePause.setObjectName("textEditTimePause")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 70, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.textEditCountMessag = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCountMessag.setGeometry(QtCore.QRect(70, 110, 31, 31))
        self.textEditCountMessag.setObjectName("textEditCountMessag")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 120, 181, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        WindowMessEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowMessEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        WindowMessEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowMessEdit)
        self.statusbar.setObjectName("statusbar")
        WindowMessEdit.setStatusBar(self.statusbar)

        self.retranslateUi(WindowMessEdit)
        QtCore.QMetaObject.connectSlotsByName(WindowMessEdit)

    def retranslateUi(self, WindowMessEdit):
        _translate = QtCore.QCoreApplication.translate
        WindowMessEdit.setWindowTitle(_translate("WindowMessEdit", "MainWindow"))
        self.pushButton.setText(_translate("WindowMessEdit", "Применить"))
        self.pushButton_2.setText(_translate("WindowMessEdit", "Отмена"))
        self.checkBoxDelPerson.setText(_translate("WindowMessEdit", "Удалять тех, кому отправили сообщение"))
        self.textEditTimePause.setHtml(_translate("WindowMessEdit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">20</span></p></body></html>"))
        self.label.setText(_translate("WindowMessEdit", "Паузы между сообщениями"))
        self.label_2.setText(_translate("WindowMessEdit", "Сек"))
        self.textEditCountMessag.setHtml(_translate("WindowMessEdit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">40</span></p></body></html>"))
        self.label_3.setText(_translate("WindowMessEdit", "Количество сообщений"))
        self.label_4.setText(_translate("WindowMessEdit", "Шт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowMessEdit = QtWidgets.QMainWindow()
    ui = Ui_WindowMessEdit()
    ui.setupUi(WindowMessEdit)
    WindowMessEdit.show()
    sys.exit(app.exec_())
